#Exercicio 073

TeamsList = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico Paranaense', 'Atletico Mineiro', 'Fortaleza', 'Sao Paulo', 'America Mineiro', 'Botafogo', 'Santos', 'Goias', 'Bragantino', 'Coritiba', 'Cuiaba', 'Ceara', 'Atletico Goianiense', 'Avai', 'Juventude')
print('=~='*30)
print('')
print('Top 5:', TeamsList[0:5])
print('')
print('=~='*30)
print('')
print('Ultimos 4 colocados:', TeamsList[-4])
print('')
print('=~='*30)
print('')
print('Times em ordem alfabética:', sorted(TeamsList))
print('')
print('=~='*30)
print('')
print(f'O Corinthians está na {TeamsList.index("Corinthians") + 1}° Posição')
print('')
print('=~='*30)