from random import randint
from time import sleep

'''Create lists to store the values generated by
the 'num4list' variable, one list for storing only
the values and another to make a copy of the data
to display to the user. The variable 'counter2' is
responsible for the stop condition of the first 'while' loop.'''
MegaSenaList = []
listForUser = []
counter2 = 1

# Ask for user input.
userInput = int(input("How many games do you want me to draw?: "))

# Loop responsible for sorting the "MegaSenaList" and creating a copy of this list for "listForUser".
while counter2 <= userInput:

    # Variable created to be the stop condition of this second 'while' loop.
    counter = 0
    
    # Loop responsible for generating the numbers for the "MegaSenaList".
    while True:
        num4list = randint(1, 60)
        
        '''Check if the generated numbers are in the list
           (Remeber that the Mega Sena doesn`t have equal numbers in the same list)
           and, if they are not in the list, this 'if' block will add the number on the list.'''
        if num4list not in MegaSenaList: 
            MegaSenaList.append(num4list)
            counter += 1
        
        # Stop condition of this second loop.
        if counter >= 6:
            break

    # Sorting the list, creating a copy of  'MegaSenaList' in 'listForUser' and clearing the first list - (MegaSenaList).
    MegaSenaList.sort()
    listForUser.append(MegaSenaList[:])
    MegaSenaList.clear()
    counter2 += 1

# Final results, here i used a 'for' loop to display the generated games.
print("-="*6, f"Drawing {userInput} games", "-="*6)
for Index, List in enumerate(listForUser):
    sleep(1.2)
    print(f"Drawing the {Index+1} game: {List}")
